// import '../models/building.dart';
// import '../models/house.dart';
//
// final List<Building> allBuildings = [
//   Building(
//     buildId: "01",
//     buildName: "Building-1",
//     buildAddress: "Address of Building-1",
//     houses: <House>[
//       House(
//         buildId: "01",
//         houseId: "G01",
//         houseNumber: "G01",
//         tenantName: "Goutham K",
//         tenantUname: "k_gout",
//         tenantIdProof: "kgoutIdProof",
//         houseAgreement: "G01Agree",
//         houseAdv: 50000.00,
//         houseRent: 10000.00,
//         houseMaintenance: 500.00,
//         isHouseWaterFixed: false,
//       ),
//       House(
//         buildId: "01",
//         houseId: "101",
//         houseNumber: "101",
//         tenantName: "Bala ",
//         tenantUname: "bala_dbs",
//         tenantIdProof: "balaIdProof",
//         houseAgreement: "G01Agree",
//         houseAdv: 52000.00,
//         houseRent: 11000.00,
//         houseMaintenance: 400.00,
//         isHouseWaterFixed: false,
//       ),
//     ],
//   ),
//   Building(
//     buildId: "02",
//     buildName: "Building-2",
//     buildAddress: "Address of Building-2",
//     houses: <House>[
//       House(
//         buildId: "01",
//         houseId: "G01",
//         houseNumber: "G01",
//         tenantName: "Goutham K",
//         tenantUname: "k_gout",
//         tenantIdProof: "kgoutIdProof",
//         houseAgreement: "G01Agree",
//         houseAdv: 50000.00,
//         houseRent: 10000.00,
//         houseMaintenance: 500.00,
//         isHouseWaterFixed: false,
//       ),
//     ],
//   ),
//   Building(
//     buildId: "03",
//     buildName: "Building-3",
//     buildAddress: "Address of Building-3",
//     houses: <House>[
//       House(
//         buildId: "01",
//         houseId: "G01",
//         houseNumber: "G01",
//         tenantName: "Goutham K",
//         tenantUname: "k_gout",
//         tenantIdProof: "kgoutIdProof",
//         houseAgreement: "G01Agree",
//         houseAdv: 50000.00,
//         houseRent: 10000.00,
//         houseMaintenance: 500.00,
//         isHouseWaterFixed: false,
//       ),
//     ],
//   ),
//   Building(
//     buildId: "04",
//     buildName: "Building-4",
//     buildAddress: "Address of Building-4",
//     houses: <House>[
//       House(
//         buildId: "01",
//         houseId: "G01",
//         houseNumber: "G01",
//         tenantName: "Goutham K",
//         tenantUname: "k_gout",
//         tenantIdProof: "kgoutIdProof",
//         houseAgreement: "G01Agree",
//         houseAdv: 50000.00,
//         houseRent: 10000.00,
//         houseMaintenance: 500.00,
//         isHouseWaterFixed: false,
//       ),
//     ],
//   ),
// ];
